### ISSUE TITLE
Hibernate package/command not availlable for Ubuntu 21.04

### ISSUE THREAD

**Issue by arch-user-france1** [ekimiateam/scripts#1]
What can I / You do?

**Comment by freechelmi** [comment]
Thanks for the feedback but we only support LTS , did you try without the hibernate package ?

**Comment by arch-user-france1** [comment]
It won't work - the 20.04 also won't work with systemctl hibernate

I close it because you only support LTS

**Comment by arch-user-france1** [comment]
And I don't need it anyways

**Comment by arch-user-france1** [comment]
Lol repopen spamming

**Comment by freechelmi** [comment]
Well our script on 20.04 Works great , But needs some change if you want pure hibernate

**Comment by arch-user-france1** [comment]
I'm using Manjaro now which supports it out-of-box

Actually Manjaro is for gaming but doesn't improve performance really - just for Minecraft
