### ISSUE TITLE
`initramfs` warning in `enablehibernate.sh`

### ISSUE THREAD

**Issue by thundersen** [ekimiateam/scripts#3]
I'm trying to set up hibernate on my system by doing all the steps from the `enablehibernate` script manually. I have verified that UUID and offset are correct:
```
➜  ~ sudo findmnt -no SOURCE,UUID -T /swapfile
/dev/mapper/ubuntu--vg-root 6e1f7737-6c88-473e-ae9c-389be09315e3
➜  ~ sudo swap-offset /swapfile
resume offset = 118351872  
➜  ~ cat /etc/initramfs-tools/conf.d/resume           
RESUME=UUID=6e1f7737-6c88-473e-ae9c-389be09315e3 resume_offset=118351872
```
But running `sudo update-initramfs -k all -u` throws a warning:
```
update-initramfs: Generating /boot/initrd.img-5.4.0-125-generic
W: initramfs-tools configuration sets RESUME=UUID=6e1f7737-6c88-473e-ae9c-389be09315e3
W: but no matching swap device is available.
```
Do you happen to know what this means? Thanks in advance!

**Comment by thundersen** [comment]
Ok, found the issue. The line in `/etc/initramfs-tools/conf.d/resume` must start with a lowercase `resume`.

**Comment by Benjixc** [comment]
Hi,

Editing /etc/initramfs-tools/conf.d/resume is not necessary when resume
value is indicated in /etc/default/grub :
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash resume=UUID=*****"
Then do:
sudo update-grub
Reboot & Test it

Benji

Le mar. 20 sept. 2022 à 10:15, thundersen ***@***.***> a
écrit :

**Comment by freechelmi** [comment]
We are still not sure if initramfs AND grub is necessary , I'll test again
